# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mergepdf.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MergePDF_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 360)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("font-family:\'微软雅黑 Light\';\n"
"font-size:18px;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color:#03030C;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setStyleSheet("background:transparent;\n"
"color:white;")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_save_merge_pdf = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_save_merge_pdf.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_save_merge_pdf.setStyleSheet("background-color:white;\n"
"color:black;\n"
"border-radius:5px;")
        self.lineEdit_save_merge_pdf.setObjectName("lineEdit_save_merge_pdf")
        self.horizontalLayout.addWidget(self.lineEdit_save_merge_pdf)
        self.pushButton_save_mergepdf = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_save_mergepdf.setMinimumSize(QtCore.QSize(120, 30))
        self.pushButton_save_mergepdf.setStyleSheet("background:deepskyblue;\n"
"border:none;\n"
"border-radius:5px;")
        self.pushButton_save_mergepdf.setObjectName("pushButton_save_mergepdf")
        self.horizontalLayout.addWidget(self.pushButton_save_mergepdf)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listWidget_pdf_list = QtWidgets.QListWidget(self.frame_4)
        self.listWidget_pdf_list.setStyleSheet("background:white;")
        self.listWidget_pdf_list.setObjectName("listWidget_pdf_list")
        self.verticalLayout_4.addWidget(self.listWidget_pdf_list)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_upload_pdf = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_upload_pdf.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_upload_pdf.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButton_upload_pdf.setStyleSheet("background:deepskyblue;\n"
"border:none;\n"
"border-radius:5px;")
        self.pushButton_upload_pdf.setObjectName("pushButton_upload_pdf")
        self.verticalLayout_3.addWidget(self.pushButton_upload_pdf)
        self.pushButton_up_pdf = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_up_pdf.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_up_pdf.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButton_up_pdf.setStyleSheet("background:#ffb219;\n"
"border:none;\n"
"border-radius:5px;")
        self.pushButton_up_pdf.setObjectName("pushButton_up_pdf")
        self.verticalLayout_3.addWidget(self.pushButton_up_pdf)
        self.pushButton_down_pdf = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_down_pdf.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_down_pdf.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButton_down_pdf.setStyleSheet("background:#ffb219;\n"
"border:none;\n"
"border-radius:5px;")
        self.pushButton_down_pdf.setObjectName("pushButton_down_pdf")
        self.verticalLayout_3.addWidget(self.pushButton_down_pdf)
        self.pushButton_delete_pdf = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_delete_pdf.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_delete_pdf.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButton_delete_pdf.setStyleSheet("background:#ffb219;\n"
"border:none;\n"
"border-radius:5px;")
        self.pushButton_delete_pdf.setObjectName("pushButton_delete_pdf")
        self.verticalLayout_3.addWidget(self.pushButton_delete_pdf)
        self.pushButton_start_merge_pdf = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_start_merge_pdf.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_start_merge_pdf.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButton_start_merge_pdf.setStyleSheet("background:#66ff14;\n"
"border:none;\n"
"border-radius:5px;")
        self.pushButton_start_merge_pdf.setObjectName("pushButton_start_merge_pdf")
        self.verticalLayout_3.addWidget(self.pushButton_start_merge_pdf)
        self.pushButton_quit = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_quit.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_quit.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButton_quit.setStyleSheet("background:#F17470;\n"
"border:none;\n"
"border-radius:5px;")
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.verticalLayout_3.addWidget(self.pushButton_quit)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "保存位置："))
        self.pushButton_save_mergepdf.setText(_translate("MainWindow", "选择保存位置"))
        self.pushButton_upload_pdf.setText(_translate("MainWindow", "上传PDF"))
        self.pushButton_up_pdf.setText(_translate("MainWindow", "上移"))
        self.pushButton_down_pdf.setText(_translate("MainWindow", "下移"))
        self.pushButton_delete_pdf.setText(_translate("MainWindow", "删除"))
        self.pushButton_start_merge_pdf.setText(_translate("MainWindow", "合并"))
        self.pushButton_quit.setText(_translate("MainWindow", "关闭"))
